#!/bin/bash
# Custom Claude Code status line — Faith x Tech x Humor
# Jesus at the center. The blood covers this code. For those with eyes to see.

input=$(cat)

MODEL=$(echo "$input" | jq -r '.model.display_name // "Claude"')
PCT=$(echo "$input" | jq -r '.context_window.used_percentage // 0' | cut -d. -f1)
COST=$(echo "$input" | jq -r '.cost.total_cost_usd // 0')

# ANSI colors
RED='\033[0;31m'
RESET='\033[0m'

PHRASES=(
  # === Pleading the Blood / Jesus-Centered (displayed in RED) ===
  "RED|Pleading the blood of Jesus over this codebase"
  "RED|The blood of Jesus covers every function and endpoint"
  "RED|By the blood of the Lamb, this code shall not fail"
  "RED|Covered by the blood — no bug shall prosper"
  "RED|Pleading the blood over every push, pull, and deploy"
  "RED|The blood of Jesus over this build — it is finished"
  "RED|Nothing crashes under the blood covering"
  "RED|Every line of code washed in the blood"
  "RED|Pleading the blood over this merge — peace, be still"
  "RED|Protected by the blood. Deployed by grace."
  "RED|The blood speaks a better word than this error log"
  "RED|Under the blood — this deploy is sealed"
  "RED|Applying the blood to the doorpost of production"
  "RED|The enemy can't touch code covered by the blood"
  "RED|Pleading the blood over every dependency"
  "RED|Covered. Protected. Deployed."
  "RED|The blood never loses its power"
  "RED|Under His blood. Under budget."
  "RED|Blood-bought code"
  "RED|The blood speaks — this build lives"

  # === Jesus at the Center ===
  "RED|Jesus is Lord — even over this codebase"
  "RED|All things were made through Him — including this feature"
  "RED|Jesus: the Author and Finisher of this code"
  "RED|In the name of Jesus, this code compiles"
  "RED|Jesus didn't quit on the third day. Neither do we."
  "RED|The name above every namespace — Jesus"
  "RED|Christ in me, the hope of a clean build"
  "RED|Jesus is the Way, the Truth, and the API"
  "RED|King of Kings and Lord of this repository"
  "RED|He is risen — and so is this deployment"
  "RED|Jesus: the original Architect"
  "RED|Yeshua runs this terminal"
  "RED|The Lion of Judah ships on time"
  "RED|Emmanuel — God with us in the code"

  # === Biblical-Tech Crossovers ===
  "Let there be code… and there was code"
  "Parting the Red Sea of merge conflicts"
  "Turning water into deployments"
  "Building the ark… one component at a time"
  "Walking on untyped waters"
  "Multiplying loaves and API endpoints"
  "Casting out demons from the codebase"
  "On the seventh iteration, we ship"
  "Raising Lazarus-level dead code"
  "Moving mountains of technical debt"
  "Wrestling this angel of a bug til daybreak"
  "David vs the Goliath of legacy code"
  "Rendering unto the DOM what is the DOM's"
  "By faith, not by console.log"
  "Flipping tables in the temple of spaghetti code"
  "Dry bones coming to life… Ezekiel 37 style"
  "Burning bush detected… not consuming memory"
  "Deploying manna from the cloud"
  "The codebase was without form and void"
  "Separating the light mode from the darkness"
  "Nehemiah mode: rebuilding these walls"
  "Converting Saul's code to Paul's"
  "Noah's git commit: saving two of everything"
  "Calling fire down on this API… Elijah style"
  "Three days in the belly of this function"
  "Solomon splitting this merge conflict wisely"
  "The walls of Jericho fell after seven builds"
  "Balaam's donkey writes better error messages"
  "The Lord gives and the garbage collector takes away"
  "Many are called but few endpoints respond"
  "Narrow is the path that leads to production"
  "The first shall be last in the callback queue"
  "For where two or three servers are gathered…"
  "Loaves, fishes, and infinite scroll"
  "Jacob worked 7 years… still faster than npm install"
  "Pentecost mode: speaking in all frameworks"
  "Storing treasures in the cloud, not localhost"
  "Rebuking this 500 error in His name"
  "No weapon formed against this deploy shall prosper"
  "Weeping may last the night but joy comes at build time"
  "Faith over stack traces"
  "Grace-compiled, Spirit-led"
  "Anointed keystrokes only"
  "God's uptime is 100%"
  "The Holy Spirit is my copilot"
  "Praying through this refactor"
  "Purpose-driven development"
  "Built by faith, shipped by grace"
  "His mercies are new every sprint"
  "Covenant code — it's unbreakable"
  "Anointed and deployed"
  "Kingdom code. Kingdom results."

  # === Short Encouraging Verses ===
  "I can do all things — Philippians 4:13"
  "Commit your work to the Lord — Proverbs 16:3"
  "Be strong and courageous — Joshua 1:9"
  "The Lord is my strength — Psalm 28:7"
  "Trust in the Lord with all your heart — Proverbs 3:5"
  "He makes all things new — Revelation 21:5"
  "With God all things are possible — Matthew 19:26"
  "The joy of the Lord is your strength — Nehemiah 8:10"
  "For such a time as this — Esther 4:14"
  "He who began a good work will complete it — Phil 1:6"
  "Plans to prosper you — Jeremiah 29:11"
  "Be still and know — Psalm 46:10"
  "Iron sharpens iron — Proverbs 27:17"
  "Whatever you do, work at it with all your heart — Col 3:23"
  "The Lord will fight for you. Be still — Exodus 14:14"
  "Delight yourself in the Lord — Psalm 37:4"
  "Do not grow weary in doing good — Galatians 6:9"
  "Greater is He in me — 1 John 4:4"
  "God is able to do exceedingly — Eph 3:20"
  "The Lord is my shepherd — Psalm 23:1"
  "By His stripes we are healed — Isaiah 53:5"
  "He is faithful — 1 Corinthians 1:9"
  "Ask and it shall be given — Matthew 7:7"
  "The battle is the Lord's — 1 Samuel 17:47"

  # === Clean Tech Humor & Dev Lingo ===
  "It works on my machine ¯\\_(ツ)_/¯"
  "Debugging: being the detective in a crime you committed"
  "99 bugs on the wall… fix one… 127 bugs on the wall"
  "Coffee in, code out"
  "sudo make it work"
  "Shipped it. No cap."
  "In Git we trust"
  "Ctrl+S is my love language"
  "404: Patience not found"
  "Cooking something crazy rn"
  "Trust the process… and the compiler"
  "We don't sleep, we deploy"
  "Talk is cheap. Show me the code."
  "It compiled. We celebrate."
  "One does not simply push to main"
  "That feeling when all tests pass"
  "Built different. Literally."
  "Works on the first try? Suspicious."
  "Making pixels obey"
  "Keep calm and clear cache"
  "Mass deploying grace"
  "Less ego, more code"
  "Shipping heat"
  "Zero bugs, all glory"
  "Built different. Called different."
  "Grinding in silence"
  "Commit and believe"
  "Clean code, clean conscience"
  "Push it live. Fear nothing."
  "Typing in tongues rn"
  "Anointed dev hours"
  "Grace > bugs"
  "The code is alive"
  "Building the future rn"
  "Obedience over optimization"
)

# Rotate phrase every ~6 seconds
INDEX=$(( $(date +%s) / 6 % ${#PHRASES[@]} ))
PHRASE="${PHRASES[$INDEX]}"

# Blood/Jesus-centered lines stay red; every other phrase cycles through the palette
PALETTE=('\033[0;36m' '\033[0;33m' '\033[0;32m' '\033[0;35m' '\033[0;34m')
if [[ "$PHRASE" == RED\|* ]]; then
  PHRASE="${PHRASE#RED|}"
  COLOR="$RED"
else
  COLOR="${PALETTE[$(( INDEX % ${#PALETTE[@]} ))]}"
fi
echo -e "${COLOR}✝ $PHRASE${RESET} | $MODEL | ${PCT}% context | \$$COST"
